#pragma once

#define VIAL_KEYBOARD_UID {0xeb, 0xf0, 0xc8, 0x1b, 0x72, 0xba, 0x7b, 0xc9}
#define PICO_FLASH_SIZE_BYTES (1 * 1024 * 1024)
#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y
#define SCROLL_MODE_INVERT_XY

#define TAPPING_TERM 180

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define VIAL_KEY_OVERRIDE_ENTRIES 4
